# used to test tool install and venv creation
[tools]
python = "3.14.8"
"github:ewhauser/shuck" = "0.2.3"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.shuck]
run = "shuck check ."
