on:
  push:
    branches:
      - main
  workflow_dispatch: {}

name: "CI"
permissions: {}

jobs:
  shuck:
    name: Shuck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Shuck
        uses: ewhauser/shuck-action@v1
        with:
          # Keep in sync with mise.toml.
          shuck-version: 0.2.3
